### ISSUE TITLE
Element preventing using the new drawer

### ISSUE THREAD

**Issue by lucas-labs** [iconify/website#31]
This transparent element shows on top of the drawer, preventing interaction with everything behind it (e.g. can't click "Download" button).

![image](https://github.com/user-attachments/assets/84068364-bb47-4e48-b24c-9cddffe4ce20)

**Comment by cyberalien** [comment]
There is no such element. Probably one of plugins in your browser is doing that.

**Comment by cyberalien** [comment]
Did you figure out which extension is causing it?

I have received a second report with identical div, but different randomised id. Also Chrome.

**Comment by cyberalien** [comment]
Added CSS to website that hides that div:
```css
body > div[style*='color-adjust'] {
	display: none !important;
	pointer-events: none !important;
}
```
Hopefully it solves your problem.

However, if you do have time, can you please check which Chrome extension is responsible for this bug or just list extensions you are using so I could check them?
